# Generated by Django 2.0.3 on 2018-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
